#Requires -Version 5.1
<#
.SYNOPSIS
    Run clang-tidy static analysis on all ARES src/ files.

.DESCRIPTION
    Uses compile_commands.json (generated by "MISRA: Generate compile database")
    and the .clang-tidy config at the project root.

    Results are written to:
      evidence/<date>/clang-tidy-<time>.txt   (per-run archive)
      evidence/<date>/clang-tidy.txt          (canonical dated file)
      evidence/latest/clang-tidy.txt          (always the latest run)

.NOTES
    Prerequisite: Run "MISRA: Generate compile database" first to produce a
    fresh compile_commands.json.
    clang-tidy binary: C:\Program Files\LLVM\bin\clang-tidy.exe (LLVM 22+).
#>

$ErrorActionPreference = 'Continue'

$clangTidy   = 'C:\Program Files\LLVM\bin\clang-tidy.exe'
$projectRoot = $PSScriptRoot | Split-Path -Parent | Split-Path -Parent
$compileDb   = Join-Path $projectRoot 'compile_commands.json'
$srcDir      = Join-Path $projectRoot 'src'

# ── Preflight checks ──────────────────────────────────────────────────────────

if (-not (Test-Path $clangTidy)) {
    Write-Error "clang-tidy not found at '$clangTidy'. Install LLVM from https://releases.llvm.org/"
    exit 1
}

if (-not (Test-Path $compileDb)) {
    Write-Error "compile_commands.json not found. Run the 'MISRA: Generate compile database' task first."
    exit 1
}

# ── Output paths ─────────────────────────────────────────────────────────────

$date      = Get-Date -Format 'yyyy-MM-dd'
$stamp     = Get-Date -Format 'HHmmss'
$base      = Join-Path $projectRoot 'evidence'
$runDir    = Join-Path $base $date
$latestDir = Join-Path $base 'latest'

New-Item -ItemType Directory -Force -Path $runDir    | Out-Null
New-Item -ItemType Directory -Force -Path $latestDir | Out-Null

$runFile      = Join-Path $runDir    ("clang-tidy-" + $stamp + ".txt")
$runCanonical = Join-Path $runDir    'clang-tidy.txt'
$latestFile   = Join-Path $latestDir 'clang-tidy.txt'

# ── Collect src/*.cpp files present in compile_commands.json ─────────────────
# We only analyse files in our src/ tree — framework headers are excluded by
# HeaderFilterRegex in .clang-tidy, and framework .cpp files are skipped here.

$db    = Get-Content $compileDb -Raw | ConvertFrom-Json
# compile_commands.json may contain relative paths (e.g. "src\main.cpp").
# Resolve each entry to an absolute path so the filter and clang-tidy invocation
# both work regardless of whether PlatformIO wrote relative or absolute paths.
$files = $db |
         Select-Object -ExpandProperty file |
         ForEach-Object {
             if ([System.IO.Path]::IsPathRooted($_)) { $_ }
             else { Join-Path $projectRoot $_ }
         } |
         Where-Object { $_ -like "$srcDir\*" -and $_ -like '*.cpp' } |
         Sort-Object -Unique

if ($files.Count -eq 0) {
    Write-Warning "No src/*.cpp files found in compile_commands.json. Has the database been regenerated after build?"
    exit 1
}

# ── Patch compile_commands.json (strip xtensa-only flags clang does not support) ──
# clang-tidy feeds the raw compile command to its own clang frontend. Flags like
# -mlongcalls are GCC/xtensa-specific and cause hard errors in clang, aborting
# analysis entirely. We write a patched copy to a temp dir and point clang-tidy
# there instead of at the original compile_commands.json.
$xtensaFlags = @(
    '-mlongcalls',
    '-fno-tree-switch-conversion',
    '-fstrict-volatile-bitfields',
    '-freorder-blocks',
    '-mtext-section-literals'
)

$tmpDir = Join-Path ([System.IO.Path]::GetTempPath()) ("ares_ct_" + [System.IO.Path]::GetRandomFileName())
New-Item -ItemType Directory -Force -Path $tmpDir | Out-Null

# ── Inject GCC implicit system include paths ──────────────────────────────────
# GCC cross-compilers have intrinsic include search paths that are NOT listed in
# compile_commands.json (C++ stdlib, C stdlib, GCC internals). clang-tidy uses
# the raw compile command and therefore misses them, causing "cstdint not found",
# "atomic not found", "stdio.h not found" errors that abort analysis and produce
# false-positive misc-unused-parameters warnings.
$xtensaToolchain = Join-Path $env:USERPROFILE '.platformio\packages\toolchain-xtensa-esp32s3'
$extraIsystems   = [System.Collections.Generic.List[string]]::new()
if (Test-Path $xtensaToolchain) {
    # Detect GCC C++ stdlib version from the directory name under include/c++
    $cxxBase    = Join-Path $xtensaToolchain 'xtensa-esp32s3-elf\include\c++'
    $gccVersion = Get-ChildItem $cxxBase -Directory -ErrorAction SilentlyContinue |
                  Select-Object -First 1 -ExpandProperty Name
    if ($gccVersion) {
        # C++ stdlib headers (cstdint, atomic, …)
        $cxxDir     = (Join-Path $cxxBase $gccVersion).Replace('\', '/')
        $cxxArchDir = (Join-Path $cxxBase "$gccVersion\xtensa-esp32s3-elf").Replace('\', '/')
        $extraIsystems.Add("-isystem `"$cxxDir`"")
        $extraIsystems.Add("-isystem `"$cxxArchDir`"")
        # GCC internal headers (stdint.h, …)
        $gccInternal = (Join-Path $xtensaToolchain "lib\gcc\xtensa-esp32s3-elf\$gccVersion\include").Replace('\', '/')
        if (Test-Path $gccInternal) { $extraIsystems.Add("-isystem `"$gccInternal`"") }
    }
    # Newlib C stdlib headers (stdio.h, …)
    $newlibInclude = (Join-Path $xtensaToolchain 'xtensa-esp32s3-elf\include').Replace('\', '/')
    if (Test-Path $newlibInclude) { $extraIsystems.Add("-isystem `"$newlibInclude`"") }
}
# ── Define GCC built-in atomic macros that clang does not predefine ───────────
# GCC's <atomic> uses __GCC_ATOMIC_*_LOCK_FREE macros which are compiler
# built-ins emitted by gcc -dM but NOT by clang.  Without them, <atomic>
# fails to compile when we inject the GCC C++ stdlib via -isystem above.
# Values for xtensa-esp32s3 (LX7, 32-bit, hardware atomics for <=32-bit):
$extraDefines = @(
    '-D__GCC_ATOMIC_BOOL_LOCK_FREE=2',
    '-D__GCC_ATOMIC_CHAR_LOCK_FREE=2',
    '-D__GCC_ATOMIC_CHAR16_T_LOCK_FREE=2',
    '-D__GCC_ATOMIC_CHAR32_T_LOCK_FREE=2',
    '-D__GCC_ATOMIC_WCHAR_T_LOCK_FREE=2',
    '-D__GCC_ATOMIC_SHORT_LOCK_FREE=2',
    '-D__GCC_ATOMIC_INT_LOCK_FREE=2',
    '-D__GCC_ATOMIC_LONG_LOCK_FREE=2',
    '-D__GCC_ATOMIC_LLONG_LOCK_FREE=0',
    '-D__GCC_ATOMIC_POINTER_LOCK_FREE=2',
    '-D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1'
)

if ($extraIsystems.Count -gt 0) {
    Write-Host ("Injecting {0} -isystem path(s) + GCC atomic macros for toolchain headers" -f $extraIsystems.Count)
} else {
    Write-Warning "xtensa toolchain not found at '$xtensaToolchain' -- cstdint/stdio.h may not resolve."
}

$patchedDb = $db | ForEach-Object {
    $cmd = $_.command
    foreach ($flag in $xtensaFlags) {
        $cmd = $cmd -replace (' ' + [regex]::Escape($flag) + '(?=\s|$)'), ''
    }
    # Inject GCC implicit system include paths so clang can find cstdint, atomic, stdio.h...
    if ($extraIsystems.Count -gt 0) {
        $cmd += ' ' + ($extraIsystems -join ' ')
    }
    # Inject GCC built-in atomic macros that clang does not predefine.
    $cmd += ' ' + ($extraDefines -join ' ')
    # Resolve relative file path to absolute so clang-tidy can locate it.
    $absFile = $_.file
    if (-not [System.IO.Path]::IsPathRooted($absFile)) {
        $absFile = Join-Path $projectRoot $absFile
    }
    [PSCustomObject]@{ directory = $_.directory; command = $cmd; file = $absFile }
}
$patchedDb | ConvertTo-Json -Depth 3 | Out-File -Encoding utf8 (Join-Path $tmpDir 'compile_commands.json')

Write-Host ("clang-tidy {0} - analysing {1} file(s) in src/" -f (& $clangTidy --version | Select-Object -First 1), $files.Count)
Write-Host ("Output: {0}" -f $runFile)
Write-Host ''

# ── Run clang-tidy on each file ───────────────────────────────────────────────

$allOutput   = [System.Collections.Generic.List[string]]::new()
$errorCount  = 0
$warningCount = 0
$sw          = [System.Diagnostics.Stopwatch]::StartNew()

$header = @(
    "clang-tidy analysis - ARES",
    ("Date  : {0}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')),
    ("Files : {0}" -f $files.Count),
    ("Tool  : {0}" -f (& $clangTidy --version | Select-Object -First 1)),
    "Config: .clang-tidy (project root)",
    ("-" * 72)
)
$allOutput.AddRange([string[]]$header)

foreach ($file in $files) {
    $relPath = $file.Replace($projectRoot + '\', '')
    Write-Host ("  Analysing {0}" -f $relPath)

    $fileOutput = & $clangTidy `
        -p $tmpDir `
        --extra-arg='-Wno-unknown-warning-option' `
        $file 2>&1

    $lines = $fileOutput | ForEach-Object { $_.ToString() }

    # Count diagnostics for the summary line.
    # Exclude clang-diagnostic-error lines that come from compiler-flag noise
    # (e.g. leftover xtensa/GCC flags that clang still reports as warnings).
    foreach ($line in $lines) {
        if ($line -match ': error:'   -and $line -notmatch '\[clang-diagnostic-') { $errorCount++ }
        if ($line -match ': warning:' -and $line -notmatch '\[clang-diagnostic-') { $warningCount++ }
    }

    if ($lines.Count -gt 0) {
        $allOutput.Add('')
        $allOutput.Add("=== $relPath ===")
        $allOutput.AddRange([string[]]$lines)
    }
}

$sw.Stop()

# ── Summary ───────────────────────────────────────────────────────────────────

$summary = @(
    '',
    ("-" * 72),
    ("Summary : {0} error(s), {1} warning(s)" -f $errorCount, $warningCount),
    ("Duration: {0:N1}s" -f $sw.Elapsed.TotalSeconds)
)
$allOutput.AddRange([string[]]$summary)

Write-Host ''
Write-Host ($summary[1])
Write-Host ($summary[2])
Write-Host ($summary[3])

# ── Persist results ───────────────────────────────────────────────────────────

$allOutput | Out-File -Encoding utf8 $runFile

try { Copy-Item -Force $runFile $runCanonical } catch {
    Write-Host 'Warning: could not refresh canonical dated file (possibly locked).'
}
try { Copy-Item -Force $runFile $latestFile } catch {
    Write-Host 'Warning: could not refresh latest file (possibly locked).'
}

Write-Host ("Results saved to: {0}" -f $runFile)

# ── Cleanup temp dir ─────────────────────────────────────────────────────────
Remove-Item -Recurse -Force $tmpDir -ErrorAction SilentlyContinue

# Exit 1 if any errors were found so VS Code marks the task as failed.
if ($errorCount -gt 0) { exit 1 }
exit 0
