#Requires -Version 5.1
<#
.SYNOPSIS
    Run clang-tidy static analysis on all ARES src/ files.

.DESCRIPTION
    Uses compile_commands.json (generated by "MISRA: Generate compile database")
    and the .clang-tidy config at the project root.

    Results are written to:
      evidence/<date>/clang-tidy-<time>.txt   (per-run archive)
      evidence/<date>/clang-tidy.txt          (canonical dated file)
      evidence/latest/clang-tidy.txt          (always the latest run)

.NOTES
    Prerequisite: Run "MISRA: Generate compile database" first to produce a
    fresh compile_commands.json.
    clang-tidy binary: C:\Program Files\LLVM\bin\clang-tidy.exe (LLVM 22+).
#>

$ErrorActionPreference = 'Continue'

$clangTidy   = 'C:\Program Files\LLVM\bin\clang-tidy.exe'
$projectRoot = $PSScriptRoot | Split-Path -Parent | Split-Path -Parent
$compileDb   = Join-Path $projectRoot 'compile_commands.json'
$srcDir      = Join-Path $projectRoot 'src'

# ── Preflight checks ──────────────────────────────────────────────────────────

if (-not (Test-Path $clangTidy)) {
    Write-Error "clang-tidy not found at '$clangTidy'. Install LLVM from https://releases.llvm.org/"
    exit 1
}

if (-not (Test-Path $compileDb)) {
    Write-Error "compile_commands.json not found. Run the 'MISRA: Generate compile database' task first."
    exit 1
}

# ── Output paths ─────────────────────────────────────────────────────────────

$date      = Get-Date -Format 'yyyy-MM-dd'
$stamp     = Get-Date -Format 'HHmmss'
$base      = Join-Path $projectRoot 'evidence'
$runDir    = Join-Path $base $date
$latestDir = Join-Path $base 'latest'

New-Item -ItemType Directory -Force -Path $runDir    | Out-Null
New-Item -ItemType Directory -Force -Path $latestDir | Out-Null

$runFile      = Join-Path $runDir    ("clang-tidy-" + $stamp + ".txt")
$runCanonical = Join-Path $runDir    'clang-tidy.txt'
$latestFile   = Join-Path $latestDir 'clang-tidy.txt'

# ── Collect src/*.cpp files present in compile_commands.json ─────────────────
# We only analyse files in our src/ tree — framework headers are excluded by
# HeaderFilterRegex in .clang-tidy, and framework .cpp files are skipped here.

$db    = Get-Content $compileDb -Raw | ConvertFrom-Json
# compile_commands.json may contain relative paths (e.g. "src\main.cpp").
# Resolve each entry to an absolute path so the filter and clang-tidy invocation
# both work regardless of whether PlatformIO wrote relative or absolute paths.
$files = $db |
         Select-Object -ExpandProperty file |
         ForEach-Object {
             if ([System.IO.Path]::IsPathRooted($_)) { $_ }
             else { Join-Path $projectRoot $_ }
         } |
         Where-Object { $_ -like "$srcDir\*" -and $_ -like '*.cpp' } |
         Sort-Object -Unique

if ($files.Count -eq 0) {
    Write-Warning "No src/*.cpp files found in compile_commands.json. Has the database been regenerated after build?"
    exit 1
}

Write-Host ("clang-tidy {0} - analysing {1} file(s) in src/" -f (& $clangTidy --version | Select-Object -First 1), $files.Count)
Write-Host ("Output: {0}" -f $runFile)
Write-Host ''

# ── Run clang-tidy on each file ───────────────────────────────────────────────
# --extra-arg flags suppress xtensa-specific compiler options that clang does
# not recognise (-mlongcalls etc.) without preventing analysis.

$allOutput   = [System.Collections.Generic.List[string]]::new()
$errorCount  = 0
$warningCount = 0
$sw          = [System.Diagnostics.Stopwatch]::StartNew()

$header = @(
    "clang-tidy analysis - ARES",
    ("Date  : {0}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')),
    ("Files : {0}" -f $files.Count),
    ("Tool  : {0}" -f (& $clangTidy --version | Select-Object -First 1)),
    "Config: .clang-tidy (project root)",
    ("-" * 72)
)
$allOutput.AddRange([string[]]$header)

foreach ($file in $files) {
    $relPath = $file.Replace($projectRoot + '\', '')
    Write-Host ("  Analysing {0}" -f $relPath)

    $fileOutput = & $clangTidy `
        -p $projectRoot `
        --extra-arg='-Wno-unknown-warning-option' `
        --extra-arg='-Wno-unused-command-line-argument' `
        $file 2>&1

    $lines = $fileOutput | ForEach-Object { $_.ToString() }

    # Count diagnostics for the summary line.
    foreach ($line in $lines) {
        if ($line -match ': error:')   { $errorCount++ }
        if ($line -match ': warning:') { $warningCount++ }
    }

    if ($lines.Count -gt 0) {
        $allOutput.Add('')
        $allOutput.Add("=== $relPath ===")
        $allOutput.AddRange([string[]]$lines)
    }
}

$sw.Stop()

# ── Summary ───────────────────────────────────────────────────────────────────

$summary = @(
    '',
    ("-" * 72),
    ("Summary : {0} error(s), {1} warning(s)" -f $errorCount, $warningCount),
    ("Duration: {0:N1}s" -f $sw.Elapsed.TotalSeconds)
)
$allOutput.AddRange([string[]]$summary)

Write-Host ''
Write-Host ($summary[1])
Write-Host ($summary[2])
Write-Host ($summary[3])

# ── Persist results ───────────────────────────────────────────────────────────

$allOutput | Out-File -Encoding utf8 $runFile

try { Copy-Item -Force $runFile $runCanonical } catch {
    Write-Host 'Warning: could not refresh canonical dated file (possibly locked).'
}
try { Copy-Item -Force $runFile $latestFile } catch {
    Write-Host 'Warning: could not refresh latest file (possibly locked).'
}

Write-Host ("Results saved to: {0}" -f $runFile)

# Exit 1 if any errors were found so VS Code marks the task as failed.
if ($errorCount -gt 0) { exit 1 }
exit 0
